### PR TITLE
Small tweak for AWS server compile

### PR DESCRIPTION
**Pull request by arthurrichards77**
I wanted to compile FGMS on an AMazon EC2 instance, so I could run a server in the AWS cloud.  Only problem I encountered was a problem for CMake finding pthread, which was documented and fixed here: https://stackoverflow.com/questions/15193785/how-to-get-cmake-to-recognize-pthread-on-ubuntu  Fix implemented and works OK on AWS.  Haven't tried anywhere else.

For interest(?) here are my notes on how to compile on AWS:

1. Launch a t2.micro Amazon Linux 2 instance.
2. Create and apply a new security group to enable inbound UDP traffic on port 5000 and TCP traffic on 5001
3. SSH to the instance, using an AWS key-pair and logging in as ec2-user (no password as it's done by keys)
4. sudo yum install cmake make gcc gcc-g++ git
5. git clone fgms
6. In the CMakeLists file, change the first project to say "PROJECT (fgms C CXX)" [avoid pthread bug]
   Source: https://stackoverflow.com/questions/15193785/how-to-get-cmake-to-recognize-pthread-on-ubuntu
7. Follow the FGMS install instructions, including sudo make install
8. Edit the example local config file and set the server.address to be the *private* IP address from ifconfig (or visible on the AWS console)
9. Test the server manually: run fgms -c <path/to/config.conf> and check you can connect from FG and by telnet, using the *public* IP address visible from the AWS console.
9. Back in the config file, set to launch as Daemon and copy the configuration file to /usr/local/etc/fgms.conf
10. As sudo, edit the /etc/crontab file and add a line "@reboot root fgms"
11. Reboot the instance from the AWS console - now the FGMS should start whenever the instance starts and there's no further need to SSH into it.

It'll cost you a little if you leave it running, so I start and stop it whenever I need it.  The private address changes each time so you'll need to keep your users up to date.

(I'd be happy to find a way to integrate this with the public MPSERVER infrastructure - just haven't got that far!  Immediate priority is a private fly-in.)

Thanks,

    Arthur

### CODE REVIEW

**Comment by pedromorgan** [comment]
hi @arthurrichards77 This is a mirror, upstream is at https://sourceforge.net/p/fgms

suggest you create a PR there ;-)

**Comment by geoffmcl** [comment]
@pedromorgan thanks for the clarification, and closing this.... I was beginning to wonder if I had missed something ;=))

But @arthurrichards77, I would still question why this `CMakeLists.txt` patch was needed, for the AWS build?

The [cmake docs](https://cmake.org/cmake/help/latest/command/project.html) states `By default C and CXX are enabled if **no** language options are given.` - my emphasis added - so adding `project( fgms C CXX )` should really do nothing... and should **not** be required...

So what exactly was the problem about finding `Threads`? 

That `stackoverflow` question is some 7 years ago... with cmake 2.8, and suggests changing `PROJECT ( Test CXX )` to `PROJECT ( Test C CXX )`, but that is because he had one, `CXX`, without the other, `C`... maybe... and I think changing it to just `PROJECT ( Test )`, like we do in fgms, would have also worked...

BTW, over the years, I have had no problem building fgms in Ubuntu... many diff versions... up to my last 18.04... using cmake 3.10.2... and in Windows 10, cmake 3.16.4... What cmake version is your AWS using...

That said, maybe there is a problem with the `target_link_libraries`... but need more info...

But as @pedromorgan indicates, this should be on `sourceforge`, the upstream repo... so maybe raise it there, in `fgms-devel` list, or maybe `Tickets`... if you still have a problem... thanks...

**Comment by pedromorgan** [comment]
Hi @geoffmcl 

Any change these patches can me merge for the [documentation](https://fgms.freeflightsim.org/)

https://sourceforge.net/p/fgms/src/merge-requests/2/

**Comment by geoffmcl** [comment]
@pedromorgan caught me just closing for today. but will get to it soonest... thanks...

**Comment by geoffmcl** [comment]
@pedromorgan, now I look at that [merge request](https://sourceforge.net/p/fgms/src/merge-requests/2/), it seems it **has** all been merged... 

And the changes appear in the docs, like in [developers_guide](https://fgms.freeflightsim.org/developers_guide.html), etc... 

Or am I missing something? Please advise... thanks...

**Comment by arthurrichards77** [comment]
Dear Geoff and Pedro

Embarrassingly, I tried reproducing the problem and got it to compile first time, without needing to do the mod this time.

I have a theory - this time I was starting from a clean install and with everything I needed installed.  Last time, I was fixing dependencies as I went (gcc and gcc-c++ weren’t there by default on my AWS instance).  I think this left me with a rather dirty cache of files that I didn’t clean up properly.

So, nothing to do!  Thanks for responding for the awesome FGMS - I’ve got great mileage out of it for ATM research.

Thanks,

    Arthur

========================================

Professor Arthur G. Richards

Director, EPSRC Centre for Doctoral Training in Future Autonomous and Robotic Systems (FARSCOPE) farscope.bris.ac.uk



Deputy Director, Bristol Robotics Lab

Tel. +44 (0) 117 328 6174 (or try UoB number below) www.brl.ac.uk



Professor of Robotics and Control, Dept. of Aerospace Engineering University of Bristol Tel. +44 (0) 117 331 5706 (or try BRL number above) seis.bristol.ac.uk/~aeagr
________________________________

**Pull request closed without merging**
